version: '3.2'

services:

  mssql:
    image: microsoft/mssql-server-linux
    restart: always
    environment:
      HOMEBREW_NO_ENV_FILTERING: 1
      ACCEPT_EULA: Y
      SA_PASSWORD: 1234Qwer

    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

    ports:
      - "1433:1433"

volumes:
  mssql_data:
  mssql_log:

