version: '3.2'

services:

  mssql:
    # image: microsoft/mssql-server-linux
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"

    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

    ports:
      - "1433:1433"

volumes:
  mssql_data:
  mssql_log:

