version: '3.2'

services:

  postgis:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: Password!2345
    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "54321:5432"

volumes:
  db_data:
