version: '3.2'

services:

  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: !234Qwer
    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  db_data:
